In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import RidgeCV
from sklearn.metrics import SCORERS
from sklearn.linear_model import LassoCV
from sklearn.linear_model import ElasticNetCV

In [2]:
df = pd.read_csv("Advertising.csv")
X = df.drop('sales',axis=1)
y = df['sales']

In [4]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [5]:
# создание новых признаков
poly_features = polynomial_converter.fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [10]:
# создаем объект для масштабирования данных
scaler = StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler()

In [12]:
X_train = scaler.transform(X_train)

In [13]:
X_test = scaler.transform(X_test)

# РЕГРЕССИЯ РИДЖ

In [15]:
ridge_model = Ridge(alpha=10)

In [16]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [17]:
test_predictions = ridge_model.predict(X_test)

In [18]:
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [20]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [21]:
RMSE

0.8946386461319674

In [22]:
MSE

0.8003783071528395

In [23]:
MAE

0.5774404204714172

In [24]:
# Производительность на обучающем наборе
train_predictions = ridge_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.5288348183025325

# Выбор значения alpha с помощью кросс-валидации

In [26]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [27]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [28]:
ridge_cv_model.alpha_

0.1

In [30]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [31]:
test_predictions = ridge_cv_model.predict(X_test)

In [32]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [33]:
MAE

0.4273774884353493

In [34]:
MSE

0.3820129881545452

In [35]:
RMSE

0.6180719926954669

In [36]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

# РЕГРЕССИЯ ЛАССО

In [44]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [45]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [46]:
lasso_cv_model.alpha_

0.49430709092258285

In [47]:
test_predictions = lasso_cv_model.predict(X_test)

In [48]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [49]:
MAE

0.6541723161252858

In [50]:
RMSE

1.130800102276254

In [54]:
test_predictions

array([13.45338009, 19.25419883, 11.92693647, 15.65984482,  9.59275546,
        8.91555193, 20.13945651, 16.8940403 , 10.30392219, 19.35585759,
       10.53851739, 13.52523076, 11.84291254, 21.97446984, 18.50473737,
       10.18416558, 12.51310389,  9.62098689,  9.58916887, 20.90872394,
        9.01385339, 18.173473  , 27.16694718, 24.24589466,  9.88609246,
       11.41696271, 21.15799353,  9.85860773, 12.19996303,  9.4393254 ,
        9.57055425, 19.39654459, 10.68194027,  8.72638276, 17.22100511,
        9.65240517, 10.54721814,  9.97920093,  8.9632026 , 10.659277  ,
       11.98376175, 10.3246849 , 11.10752122,  9.02040466, 11.57917154,
       10.78030361,  8.57798137, 15.15282195, 12.72136342, 21.35302125,
       10.86548461, 12.78550905, 14.91137805, 11.70074134, 11.30228394,
        8.43176178, 24.92405026, 10.66203455, 17.58679446, 14.93460903])

In [59]:
# lasso работает хуже, но зато можно понять от каких признаков зависит целевая переменная и 
# результаты lasso смогла получить используя только 2 признака

# также чтобы сделать результат лучше, можео понастраивать гиперпараметры, те самым
# будет больше усилий на поиск оптимальной модели
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

#  Elastic Net

In [60]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [61]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [62]:
elastic_model.l1_ratio_

1.0

In [64]:
elastic_model.alpha_

0.004943070909225827

In [66]:
test_predictions = elastic_model.predict(X_test)

In [67]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [68]:
MAE

0.566326211756945

In [69]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])